### PR TITLE
Fix JAVASERVERFACES-4120: Ajax file upload fails when com.sun.faces.namespaceParameters is set to true

### PR DESCRIPTION
**Pull request by stiemannkj1**

### CODE REVIEW

**Comment by stiemannkj1** [comment]
@vsingleton,
[Reproducer for this issue and tester for this fix.](https://github.com/stiemannkj1/ajax-fileupload-reproducer)

**Comment by stiemannkj1** [comment]
@vsingleton, looks like this was ~~merged~~ (actually re-implemented ~~or copy/pasted~~ without merging :disappointed:) here: https://github.com/javaserverfaces/mojarra/commit/d92c13aa1f5959bab94a7b7610ff633584d0ce3b.

**Comment by iir0221** [comment]
sorry @stiemannkj1 . I didn't notice your pull request.  I will merge your pull next time.

**Comment by xinyuan-zhang** [comment]
sorry @stiemannkj1 . I didn't notice your pull request. I will merge your pull next time.

**Comment by stiemannkj1** [comment]
@emma0221, thanks. And thanks for fixing this.

**Pull request closed without merging**
