### PR TITLE
Avoid namespaceing OutputLinkRenderer params

### PR DESCRIPTION
**Pull request by stiemannkj1**
@vsingleton,
Please test [this commit](https://github.com/vsingleton/mojarra_read-only_mirror/pull/12/commits/5e72af57434aa0f30c6a891c62876d26894649e1) against the Mojarra test suite and merge this into Mojarra master.

### CODE REVIEW

**Comment by BalusC** [comment]
How does this comply https://github.com/stiemannkj1/mojarra/commit/62732d26cc30ea66827f2aef37ef17b597052d28#diff-fa3652ac816310d030611acbc577b9b4 ?

**Comment by stiemannkj1** [comment]
@BalusC, Hmm... good catch. We are looking into it now.

**Comment by stiemannkj1** [comment]
@ngriffin7a,
It looks like you provided [the patch that BalusC mentioned](https://java.net/jira/secure/attachment/53364/JAVASERVERFACES-3276-jsf22.patch) in order to fix [JAVASERVERFACES-3276](https://java.net/jira/browse/JAVASERVERFACES-3276). The fix was also applied to JSF 2.2. Should that change be backed out (as we've done in this commit)? Or was that change correct (meaning our issue with `OutputLinkRender` needs to be fixed elsewhere)?

**Comment by ngriffin7a** [comment]
@BalusC Indeed, good catch! Thank you for pointing that out. The addition of the separatorChar in JSF 2.3 exposed an issue caused by my patch for [JAVASERVERFACES-3276](https://java.net/jira/browse/JAVASERVERFACES-3276). More details below...

@stiemannkj1 Regarding the "paramWritten" boolean, that part of the patch for [JAVASERVERFACES-3276](https://java.net/jira/browse/JAVASERVERFACES-3276), was correct since the [FacesBridge TCK tests for values that contain a query-string](https://github.com/liferay/liferay-faces-bridge-impl/blob/master/tck/bridge-tck-main-portlet/src/main/webapp/tests/redisplayResourceAjaxResult.xhtml#L15). However, it was not correct for me to have included the part that prepends the namespace prefix. For more information, see [JAVASERVERFACES-4209](https://java.net/jira/browse/JAVASERVERFACES-4209).

@vsingleton Please continue your testing and if all goes well, commit Kyle's fix referencing [JAVASERVERFACES-4209](https://java.net/jira/browse/JAVASERVERFACES-4209). I will provide backport pull requests for Mojarra 2.2 and 2.1 as well.

**Pull request closed without merging**
